apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  type: kv-v2
  mount: secret
  path: dev/db-credentials
  destination:
    name: db-credentials # Creates a Kubernetes Secret named db-credentials
    create: true
  refreshAfter: 60s
  vaultAuthRef: default
