apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - service-account.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml
  - vso/vault-auth.yaml
  - vso/vault-connection.yaml
  - vso/vault-static-secret.yaml
