apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: py-app-service-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: py-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
